#!/usr/bin/env bash

set -euox pipefail

# Source the file that forwards the HM-related variables from the host when running in
# a container.
source /root/project_env.sh || true

cd /config/
/usr/bin/git pull || true
/usr/local/bin/harbormaster run -d /main -c /config/harbormaster.yml
